### ISSUE TITLE
Support for media keys

### ISSUE THREAD

**Issue by tristan-k** [maculateConception/aural-player#11]
Please add support for media keys. Maybe collaborate with [BeardedSpice](https://github.com/beardedspice/beardedspice/issues/900). Thanks for developing such an awesome player.

**Comment by maculateConception** [comment]
Thanks for the feedback. Yes, media key support would be great to have, and I have looked into it and tried implementing it with no luck so far.

I found some Objective C solutions online that supposedly work, but I was not able to find a working Swift solution.

When I tried implementing this, it would not only trigger the key on my app but also let the key event propagate to other media apps like iTunes and iTunes would open (not desirable behavior).

**Comment by maculateConception** [comment]
Media keys support has been added. Please download release version 1.3.0 [here](https://github.com/maculateConception/aural-player/releases/tag/1.3.0) and follow [these instructions](https://github.com/maculateConception/aural-player#enabling-media-keys-support-available-with-version-130-onwards) to enable the support on macOS.

I now consider this issue closed. 

Thanks for your interest in Aural Player, and best regards,
maculateConception
