### ISSUE TITLE
Saving window layout and playlist view preference

### ISSUE THREAD

**Issue by clustor** [maculateConception/aural-player#14]
I prefer "Vertical player and playlist" window layout but after restarting the app this layout is not persisted. I do not see an option in preference to make this stick.

Similarly, I prefer to view the playlist in "Album" mode all the time and it would be great if this setting can be persisted as well instead of always opening in "Tracks" view.

**Comment by maculateConception** [comment]
Hi, thanks for letting me know about this.

The window layout should be persisted, so what you're seeing is a bug. I have not spent any time on this project recently but will take a look.

Also, I will see about adding an option so that the playlist can always open in Album or other views per user preference.

Thank you.

**Comment by maculateConception** [comment]
By the way, I have added the new feature you requested - being able to set and persist a preferred playlist view.

Please download the [latest release](https://github.com/maculateConception/aural-player/releases/latest)

**Comment by clustor** [comment]
Thank you very much. Both of them work now with the release and your instructions.

**Comment by maculateConception** [comment]
Hi, I just wanted to add one more thing for clarification, in case it is a problem for you. It is a subtle difference between the 2 view options for window layout.

The "Remember layout from last app launch", will not only remember the layout (i.e. vertical player and playlist) but also the position of the windows. Let's say you had dragged the app windows to the far right of the screen, and then quit the app. The next time you launch the app, the windows will appear exactly how and where you had positioned them the previous time (i.e. far right of the screen).

On the other hand, the "Start with layout" option will reposition them in a fixed place on each app startup. I believe the "Vertical P & P" will always start in the center of the screen, if this preference setting is chosen.

Just wanted to point this out.
