### ISSUE TITLE
Is the icon off-center on purpose?

### ISSUE THREAD

**Issue by runrunrirun** [maculateConception/aural-player#16]
It's kind of activating my OCD ;)

**Comment by maculateConception** [comment]
Hehe ... sorry about that :)

Which icon are you referring to ? The main app logo that says "Aural" ?

**Comment by maculateConception** [comment]
I have fixed the playing track indicator alignment in the playlist. You can verify it in the upcoming release if you want.

Since I haven't heard back from you, I'm going to assume ^ this is what you were referring to, and close the issue. You can reopen it if this was not it.
