### ISSUE TITLE
Audio pan to left with certain FLAC and mp3 files/missing vocals on right channel

### ISSUE THREAD

**Issue by luvBuzz** [maculateConception/aural-player#19]
Hi! 
Thanks for the great program. Unfortunately I experience weird behaviour with some FLAC and mp3 files. 

The audio seems to be off center. The vocals and instruments which should be in the middle are only audible on the left channel. The right channel itself sounds like something is missing, as if you would listen to the sourround channel of a 5.1 system (although the info says 2ch or stereo).

The audio for the said files is fine with IINA.

Appears on Macbook and iMac on different speakers/headphones and audio interfaces.
- Aural 2.2.0
- macOS Catalina 10.15.6

**Comment by maculateConception** [comment]
Hi, thanks for reporting this issue. 

Yes, I have noticed this behavior too. I have noticed it only with FLAC files, however. Initially, I suspected that it may something to do with the AVAudioEngine framework and the fact that native FLAC support is relatively new to macOS (was introduced only in High Sierra 10.13). I wasn't aware that it also happens with some MP3s.

I am currently away from the project for a little while, but I will certainly investigate this further when I return to working on this project.

**Comment by maculateConception** [comment]
@luvBuzz Hi, is there any way you can share any of the problem files with me so that I can reproduce and try to fix this issue ?  I'd really appreciate it.

If not, no worries.

**Comment by luvBuzz** [comment]
@maculateConception Hi! I've updated to 2.6 and BigSur now and it seems like those .flac files can't be played anymore ("File is not a playable audio track. Is it a valid audio file of a supported format ?").
Unfortunately I can't remember exactly which songs were affected so I'm not a 100% sure. 
If you could send me a mail adress, i can send you one of those files.

**Comment by maculateConception** [comment]
Wow, that's a pretty bad bug. My email address is aural.student@gmail.com

Please send me the FLAC file that 2.6 was not able to play. I'll look into that issue first and then try to reproduce the panning issue. Thanks !

By the way, I'm working on v2.7, which uses ffmpeg to decode FLAC files ... this might fix the panning issues altogether, I'm not sure. And v2.7 should come out in a few days.

**Comment by luvBuzz** [comment]
I can confirm that v2.7 fixed this issue. The mentioned files are now playable. 
Just for clarification: I think those same files had the panning issue in the older versions. That is why I think this issue is now solved completely and can be closed.

Great work!

**Comment by maculateConception** [comment]
Thanks very much for the report on v2.7. Good news.

However, could you please send me the file that 2.6 couldn't play ? I would like to find out why that happened ... knowing that would really help me. If possible, thanks.

I'm closing the issue. Cheers !
