### ISSUE TITLE
Chinese Support issue

### ISSUE THREAD

**Issue by RockTraveler** [maculateConception/aural-player#20]
Hi Sir,

I am a Chinese user and I had lots of tracks from China, could you please let me know how to configure the charset to support the Chineses display.

**Comment by maculateConception** [comment]
Hi,

I'm not sure how to go about doing this. I have never worked with non-English charsets before, so I need some time to figure it out.

Thanks.

**Comment by maculateConception** [comment]
Hi, I have just released support for custom fonts and am wondering if this might provide a solution for your problem. Please download [v2.5.0](https://github.com/maculateConception/aural-player/releases/tag/2.5.0) and try using your custom font that contains Chinese characters ... see if that works for you.

**Comment by maculateConception** [comment]
Since I haven't heard back from you, and the exact requirements are unclear, I am closing this issue for now. Please reopen if you can provide more details.

**Comment by ReekyStive** [comment]
I am also a Chinese user, and I have not encountered Chinese character display issue on the latest version. I am using macOS Big Sur.

**Comment by maculateConception** [comment]
Thanks for the info, ReekyStive ! You rock 🥇
