### ISSUE TITLE
macOS playback control not available in Control Center

### ISSUE THREAD

**Issue by ReekyStive** [maculateConception/aural-player#28]
When Aural is playing a track, the macOS control center does not display the track information. This makes it impossible to use keyboard shortcuts to control music playback.

<img width="625" alt="Screen Shot 2021-06-18 at 04 51 37" src="https://user-images.githubusercontent.com/26853900/122471010-52e8f980-cff1-11eb-9b41-6714b633e353.png">

## System information
```
Processor: Apple M1
System: macOS Version 11.4 (20F71)
Aural Version: v3.0.0
```

**Comment by maculateConception** [comment]
Hi, thanks for the feedback.

Have you enabled media keys ? I assume you want to control playback using the standard macOS media keys ? If so, please follow the simple instructions here: [Enabling media keys support](https://github.com/maculateConception/aural-player/wiki/Enabling-media-keys-support).

If you are not referring to media keys, can you please clarify the issue ? I thought that the control center is only for macOS's built-in features / apps. I didn't know that 3rd party app controls can appear there. Are there other apps whose controls show up in Control Center ?

Thanks,
maculateConception

**Comment by ReekyStive** [comment]
I noticed this page: https://github.com/maculateConception/aural-player/wiki/Enabling-media-keys-support

It seems possible to use the media keys to control playback, but is it possible to use the system's native interface? That way, no additional permissions are needed, and system can control the playback.

**Comment by ReekyStive** [comment]
Many third-party software such as Spotify and audio and video in Chrome will appear in the macOS Control Center during playback. I don't know how to implement it, but I think there must be an interface to tell the system software is playing music. Hope this helps!

**Comment by maculateConception** [comment]
Oh ok, I was not aware that such a thing is possible :) Let me do some research, and that would be a nice thing to implement.

Thanks again, and I will let you know of my progress with this.

Cheers!

**Comment by ReekyStive** [comment]
Cheers! XD

**Comment by maculateConception** [comment]
![remoteControl1](https://user-images.githubusercontent.com/30028539/122550223-0cc38280-d051-11eb-8ddb-06977763791a.png)

![remoteControl2](https://user-images.githubusercontent.com/30028539/122550243-1220cd00-d051-11eb-9c4f-2a7b708c2822.png)

**Comment by maculateConception** [comment]
Hi, I have implemented and released the feature you requested. I have also reduced the default playlist window height ("Vertical full stack" window layout) as per your suggestion. 

Thanks very much for your valuable feedback. I have mentioned your name in the release. 😊

I will wait a few days for you to try it out and close this issue if you're satisfied. If I don't hear back from you in a few days, I'll go ahead and close it myself.

[Version 3.1.0 release](https://github.com/maculateConception/aural-player/releases/tag/3.1.0)

**Comment by ReekyStive** [comment]
It works very well! Even if I did not open "Respond to media keys" option (I guess this option requires additional permissions to detect keystrokes).

<img width="850" alt="Screen Shot 2021-06-25 at 02 49 09" src="https://user-images.githubusercontent.com/26853900/123317355-80d5bd00-d560-11eb-9140-0f9f594cf97b.png">

<img width="506" alt="Screen Shot 2021-06-25 at 02 49 55" src="https://user-images.githubusercontent.com/26853900/123317362-83381700-d560-11eb-8e87-22a1362500c7.png">

Through Remote Control, you can use the headset button to control, automatically pause or play in some cases, and so on. The playback is controlled by the system.

Maybe the "Media Keys" option is no longer needed?

Thanks for your work.

**Comment by ReekyStive** [comment]
Or maybe you can keep the "Media Keys" option to implement extra functions such as "hold to seek".

**Comment by maculateConception** [comment]
Hey, thanks for letting me know that it works ! This kind of feedback is valuable to me.

I have 2 questions for you, because I did a lot of research but was not able to find answers:

1 - Do you have a headset that can control playback ? What kind of headset is it (make and model) ? I'm asking because I wonder if it will work with my headset. I have a Sony wireless headset and would like to test it out if it is possible.

2 - Also, is this feature useful in Catalina or older systems ? I read that Control Center is only on Big Sur, so how would users make use of Remote Control ? Through Apple accessories ? Are there Apple Remotes that work with Macs ? I saw one for tvOS but nothing for macOS.

**Comment by ReekyStive** [comment]
1. I think all headsets with control buttons should work, whether they are wireless or wired. Because playback is controlled by the system, if the media keys on the keyboard work, the headset control should also work. In actual tests, both my Honor FlyPods3 (wireless headphones) and Audio-Technica CK350iS (wired headphones) worked.
2. I only started using macOS this year, so I have only used macOS Big Sur. Controlling playback through the buttons on the headset is a very basic function, I don't think the old macOS does not support it. After my research, I found that the old macOS will also focus "Media Keys" on the last App that played media. Then, the headset control and media keys can control playback.

**Comment by maculateConception** [comment]
Ok great, thanks. This is all very useful information. I will perform testing with my own headphones and update the release notes to include that playback can be controlled through headphones.

I'm glad you suggested implementing this feature 😊.
