### ISSUE TITLE
Keyboard Shortcut / Hotkey for Shuffle and Repeat

### ISSUE THREAD

**Issue by peking84** [maculateConception/aural-player#30]
I was playing with the pitch shift, time stretch like we used to act like djs in our teenage years with JetAudio and the winamp plugins.
Wow! Aural player is the greatest invention since I hooked up on Winamp at version 1.2. 
Added the player to the must-have OS X program list...

One request I'd like to make (which I have not found in the [Corresponding wiki section](https://github.com/maculateConception/aural-player/wiki/Handy-keyboard-shortcuts)). 
Can you add two additional handy keyboard shortcut for the shuffle and the repeat button?
Multiple choices could be round-robin or separate keys.
//Reference Aural Player v3.3.1
//["Sequencing - repeat track, repeat all (playlist / group), shuffle"
](https://github.com/maculateConception/aural-player/wiki/Features)

**Comment by maculateConception** [comment]
Hi @peking84,

As you requested, I have implemented keyboard shortcuts to toggle repeat and shuffle mode.

Toggle Repeat Mode: ⌥R
Toggle Shuffle Mode: ⌥S

This new feature went out in the latest release v3.4.1. Please download it [from here](https://github.com/maculateConception/aural-player/releases/tag/v3.4.1) and try it out.

I have also updated the [shortcuts wiki page](https://github.com/maculateConception/aural-player/wiki/Handy-keyboard-shortcuts) with the new shortcuts.

Thanks for the suggestion. Cheers,
mC

**Comment by peking84** [comment]
Hi @maculateConception 

Works like a charm. 
Thanks for taking time to implement it and to follow up!

Happy holidays!

Cheers
Mark
