### ISSUE TITLE
Use GitHub releases

### ISSUE THREAD

**Issue by hbbio** [maculateConception/aural-player#8]
Please use GitHub releases to host the `dmg`!

As of now, your repository is cluttered with revisions of the dmg file (which you don't need). You will also need to properly [remove the files](https://help.github.com/articles/removing-files-from-a-repository-s-history/).

**Comment by maculateConception** [comment]
Hi, thanks for the suggestion. I will take a look into doing that. I have thought about it myself, but have been too lazy to look into it.

**Comment by hbbio** [comment]
Thanks for the answer, it's a very interesting project btw congrats for that.

I guess you're not going to automate releases with CI (harder with a Mac), but you can check an [easy-to-use CLI](https://github.com/aktau/github-release).

And for deleting history (the repo is >500Mb), you can look at the so-called [nuclear option](https://help.github.com/articles/removing-sensitive-data-from-a-repository/).

**Comment by maculateConception** [comment]
Thanks again for the CLI tip and the feedback on the project ! I'm glad you brought up Git releases, because I would like to get more organized here. I've just been really busy with development work.

I think that for this project, CI might be overkill. But, I will definitely look into manual releases once the dev work slows down.

Cheers !

**Comment by maculateConception** [comment]
> Please use GitHub releases to host the `dmg`!
> 
> As of now, your repository is cluttered with revisions of the dmg file (which you don't need). You will also need to properly [remove the files](https://help.github.com/articles/removing-files-from-a-repository-s-history/).

Hi, I am now using GitHub releases. Thanks for the suggestion. Cheers !
