### ISSUE TITLE
Greyness on title bar

### ISSUE THREAD

**Issue by yougotwill** [maculateConception/aural-player#9]
Thanks for making this awesome app and keep up the good work! Once I upgrade my mac and learn enough swift I'm keen to start contributing :)

I'm on 10.12.6 for the record.

<img width="1086" alt="screen shot 2018-12-10 at 12 17 21 pm" src="https://user-images.githubusercontent.com/14887287/49726004-aa19f080-fc75-11e8-91e4-99aa15344d10.png">

**Comment by maculateConception** [comment]
Hello, I have put out a new release of the app, which contains fixes for the issue you reported. Just download the latest Aural.dmg file. 

Feel free to test it out and let me know if it appears fixed on your end.

Thanks again, for reporting this issue. Such reports benefit everyone using the app and help me improve the app.

I now consider this issue closed.

Cheers !
